// src/lib/player/TrackList.svelte
<script lang="ts">
	import { album, track, playing } from '$lib/stores/nowPlaying';
	let tracks = [];
	let artistList = '';
	$: {
		tracks = $album?.tracks?.items || [];
		tracks.sort((a, b) => a?.track_number - b?.track_number);
		artistList = $album.artists.map((artist) => artist.name).join(', ');
	}
</script>

<div class="pl-6">
	{#if $album}
		<h2 class="font-bold text-5xl my-2 mt-6">
			{$album?.name}
		</h2>
		<h3 class="text-3xl text-brand-grey-400 mb-8">{artistList}</h3>
		<ol class="list-decimal pl-4 two-col text-2xl py-2 font-thin">
			{#each tracks as albumTrack}<li
					class:now-playing={$track.name.toLocaleLowerCase() ===
						albumTrack.name.toLocaleLowerCase()}
				>
					{#if $track.name.toLocaleLowerCase() === albumTrack.name.toLocaleLowerCase()}{#if $playing}▶{:else}&#1520;{/if}{/if}
					{albumTrack?.name}
				</li>{/each}
		</ol>
	{/if}
</div>

<style>
	.now-playing {
		@apply font-bold animate-pulse;
	}

	.two-col {
		columns: 2;
	}
</style>

// components/TrackList.tsx
import EqualizerIcon from "@components/Icons/EqualizerIcon";

export default function TrackList({ nowPlaying }) {
  const { album, track, playing, paused } = nowPlaying;
  if (!album.name) {
    return <></>;
  }
  return (
    <>
      <h2 className="my-2 text-2xl font-bold text-brand-grey-50">
        {album.name} ({album.artist})
      </h2>
      <div className="flex-grow h-0">
        <ol className="flex flex-col flex-wrap w-full h-full ml-4 list-decimal">
          {album.tracks.map((albumTrack: any, index: number) => {
            return (
              <li
                key={albumTrack.id}
                className=""
                style={{
                  display: "inline-list-item",
                }}
              >
                <div className="relative flex items-center">
                  {albumTrack.name} -{" "}
                  {Math.floor(albumTrack.duration_ms / 60000)}:
                  {("" + (Math.floor(albumTrack.duration_ms / 1000) % 60))
                    .length === 2
                    ? Math.floor(albumTrack.duration_ms / 1000) % 60
                    : "0" + (Math.floor(albumTrack.duration_ms / 1000) % 60)}
                  s
                  {albumTrack.name === track?.name && playing && !paused ? (
                    <span className="absolute top-0 ml-2 -left-14">
                      <EqualizerIcon />
                    </span>
                  ) : (
                    ""
                  )}{" "}
                </div>
              </li>
            );
          })}
        </ol>
      </div>
    </>
  );
}
